// Generated by CoffeeScript 1.9.1
define('mods/index',['_lib/lazyload','mods/_index/slider','mods/_index/vmctrl'],function(lazyload, Slider, vmctrl) {
    var init;
    init = function() {
        Slider.init();
        $('img').lazyload({
            placeholder: STATIC_PATH + '/img/dot.png'
        });
        vmctrl.run(function() {
            $(window).resize(function() {
                $("#iBar").css({
                    'height': $(window).height()
                });
            });
        });
    };
    init();
});
